### ISSUE TITLE
collecting amount of stationed troops

### ISSUE THREAD

**Issue by didadadida93** [breuerfelix/king-bot#36]
![screenshot from 2018-08-25 11-56-54](https://user-images.githubusercontent.com/25358436/44615191-1eaf5780-a85e-11e8-9187-21cbab548093.png)
i will create a function that collecting amount of stationed troops.

**Comment by scriptworld-git** [comment]
my thoughts:
return type could be a dict, key will be an integer (see chapter upgrade units in smithy) and value will be the actual value.

![screenshot](http://prntscr.com/knpfhg)

you can take this unitType value, and add 10 for teuton and 20 for gaul. this would get you the correct key :)  
just my thought ! but im open minded :D

**Comment by didadadida93** [comment]
instead of using number as key, i think it will better if we use troop names
what do you think? :thinking:

**Comment by scriptworld-git** [comment]
ye why not! this will be easier to understand.  
i guess ill change upgrades units in smithy to strings also, or should we use an enum ? that would be the last option :D

**Comment by didadadida93** [comment]
#38
